services:
  postgres:
    container_name: postgre_container
    image: postgres
    environment:
      POSTGRES_USER: rajesh
      POSTGRES_PASSWORD: rajesh
#      PGDATA: /data/postgres
    volumes:
      - postgres-data:/var/lib/postgresql
    ports:
    - "5432:5432"

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    # volumes:
    #   - pgadmin: "/var/lib/pgadmin"
    ports:
    - "5050:80"

volumes:
  postgres-data:
    driver: local
#    pgadmin: