spring:
  application:
    name: SpringBootSecurity
  datasource:
    username: root
    password: rajesh31
    url: jdbc:mysql://localhost:3306/mydb
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
$key: hjjhbcjhbcjbjasbcljabcljsbvjfdsbvlgvbjhsbdjlhffpigjoihjkjfbdwyuguicbdkug    
    